package net.ukr.kiyashko.lab2_11;

public class TestException {
    public static void main(String argv[]) {
       /* try {
            int a=5;
            int b=0;
            String c="test";
            System.out.println("values: " + a/b+c);
            throw new Exception("get");
        }
       /* catch (ArithmeticException e){
            System.out.println("Деление на ноль");
        }
        catch (Exception e){
            System.out.println("Error "+e.getMessage());
        }
        finally {
            System.out.println("Itog: ");

        }*/




    }
}
